# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{smi-ffi}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mixtli"]
  s.date = %q{2010-12-29}
  s.default_executable = %q{smidump.rb}
  s.description = %q{ffi bindings for libsmi}
  s.email = %q{ronmcclain75@gmail.com}
  s.executables = ["smidump.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/smidump.rb",
     "c/Makefile",
     "c/a.out",
     "c/test",
     "c/test.c",
     "c/test.o",
     "interface/smi.h",
     "lib/smi.rb",
     "lib/smi/config.rb",
     "lib/smi/module.rb",
     "lib/smi/node.rb",
     "lib/smi/wrapper.rb",
     "spec/mibs/IF-MIB",
     "spec/mibs/RFC1213-MIB",
     "spec/smi-ffi_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mixtli/smi-ffi}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby Interface to libsmi}
  s.test_files = [
    "spec/smi-ffi_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
  end
end

